import type { NotebookWord } from "./types";

export const MOCK_NOTEBOOK_WORDS: NotebookWord[] = [
  // ── Japanese ──────────────────────────────────────────────────
  {
    id: "ja-v1",
    word: "勉強",
    reading: "べんきょう",
    pos: "Danh từ · Động từ",
    meaning: "Học (tập, ôn bài)",
    example: "毎日日本語を勉強しています。",
    exampleVi: "Tôi học tiếng Nhật mỗi ngày.",
    status: "learning",
    lang: "ja",
    urgency: "due",
    nextReview: "Hôm nay 18:00",
    reviewReason: "Golden Time đang đến hạn, ôn bây giờ sẽ giữ nhịp nhớ.",
    weakSkill: { skill: "usage", label: "Cách dùng", evidence: "Thường nhầm 勉強 trong câu ghép." },
    phrases: ["勉強する", "勉強になる", "勉強不足"],
    relatedWords: [
      { id: "ja-rel1", word: "学習", reading: "がくしゅう", meaning: "Học tập (formal)" },
      { id: "ja-rel2", word: "習う", reading: "ならう", meaning: "Học theo thầy" },
    ],
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 62 },
      { skill: "listening",   label: "Nghe",           accuracy: 55 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 70 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 40 },
      { skill: "collocation", label: "Collocation",    accuracy: 35 },
    ],
  },
  {
    id: "ja-v2",
    word: "約束",
    reading: "やくそく",
    pos: "Danh từ · Động từ",
    meaning: "Lời hứa, hẹn hò",
    example: "約束を守ることが大切です。",
    exampleVi: "Giữ lời hứa là điều quan trọng.",
    status: "review",
    lang: "ja",
    urgency: "due",
    nextReview: "Ngày mai 09:00",
    reviewReason: "Kỹ năng Collocation còn dưới 50% — chưa thuộc cụm 約束を守る / 約束を破る.",
    weakSkill: { skill: "collocation", label: "Collocation", evidence: "Chưa thuộc cụm 約束を守る / 約束を破る." },
    phrases: ["約束を守る", "約束を破る", "約束する"],
    relatedWords: [
      { id: "ja-rel3", word: "約束する", reading: "やくそくする", meaning: "Hứa hẹn (động từ)" },
      { id: "ja-rel4", word: "予約", reading: "よやく", meaning: "Đặt trước" },
    ],
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 80 },
      { skill: "listening",   label: "Nghe",           accuracy: 75 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 65 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 55 },
      { skill: "collocation", label: "Collocation",    accuracy: 48 },
    ],
  },
  {
    id: "ja-v3",
    word: "親切",
    reading: "しんせつ",
    pos: "Danh từ · Tính từ",
    meaning: "Tốt bụng, thân thiện",
    example: "彼女はとても親切な人です。",
    exampleVi: "Cô ấy là người rất tốt bụng.",
    status: "mastered",
    lang: "ja",
    urgency: "ok",
    nextReview: "3 ngày nữa",
    reviewReason: "Đã thành thạo. LexiPath theo dõi định kỳ để duy trì.",
    phrases: ["親切にする", "親切心", "親切な人"],
    relatedWords: [
      { id: "ja-rel5", word: "優しい", reading: "やさしい", meaning: "Nhẹ nhàng" },
      { id: "ja-rel6", word: "丁寧", reading: "ていねい", meaning: "Lịch sự" },
    ],
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 95 },
      { skill: "listening",   label: "Nghe",           accuracy: 88 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 90 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 82 },
      { skill: "collocation", label: "Collocation",    accuracy: 78 },
    ],
  },
  {
    id: "ja-v4",
    word: "経験",
    reading: "けいけん",
    pos: "Danh từ · Động từ",
    meaning: "Kinh nghiệm, trải nghiệm",
    example: "社会経験を積むことが大切です。",
    exampleVi: "Tích lũy kinh nghiệm xã hội là điều quan trọng.",
    status: "learning",
    lang: "ja",
    urgency: "due",
    nextReview: "Hôm nay 20:00",
    reviewReason: "Bạn nhầm けいけん với けいかく khi nghe trong phiên gần nhất.",
    weakSkill: { skill: "listening", label: "Nghe hiểu", evidence: "Nhầm けいけん với けいかく khi nghe. Cần luyện thêm." },
    relatedWords: [
      { id: "ja-rel7", word: "体験", reading: "たいけん", meaning: "Trải nghiệm thực tế" },
      { id: "ja-rel8", word: "経歴", reading: "けいれき", meaning: "Quá trình kinh nghiệm" },
    ],
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 60 },
      { skill: "listening",   label: "Nghe",           accuracy: 52 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 68 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 44 },
      { skill: "collocation", label: "Collocation",    accuracy: 38 },
    ],
  },
  {
    id: "ja-v5",
    word: "努力",
    reading: "どりょく",
    pos: "Danh từ · Động từ",
    meaning: "Nỗ lực, cố gắng",
    example: "毎日努力することが成功の秘訣です。",
    exampleVi: "Nỗ lực mỗi ngày là bí quyết thành công.",
    status: "new",
    lang: "ja",
    urgency: "none",
    reviewReason: "Từ mới — bắt đầu học để LexiPath bắt đầu xếp lịch ôn.",
    phrases: ["努力する", "努力家", "努力の成果"],
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 20 },
      { skill: "listening",   label: "Nghe",           accuracy: 15 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 18 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 12 },
      { skill: "collocation", label: "Collocation",    accuracy: 10 },
    ],
  },
  {
    id: "ja-v6",
    word: "感謝",
    reading: "かんしゃ",
    pos: "Danh từ · Động từ",
    meaning: "Lòng biết ơn, cảm ơn",
    example: "先生に感謝の気持ちを伝えました。",
    exampleVi: "Tôi đã truyền đạt lòng biết ơn đến thầy giáo.",
    status: "forgetting",
    lang: "ja",
    urgency: "overdue",
    nextReview: "Quá hạn 2 ngày",
    reviewReason: "Quá hạn 2 ngày — ôn ngay để không quên.",
    phrases: ["感謝する", "感謝の気持ち", "心から感謝"],
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 45 },
      { skill: "listening",   label: "Nghe",           accuracy: 38 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 50 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 32 },
      { skill: "collocation", label: "Collocation",    accuracy: 28 },
    ],
  },
  {
    id: "ja-v7",
    word: "練習",
    reading: "れんしゅう",
    pos: "Danh từ · Động từ",
    meaning: "Luyện tập, thực hành",
    example: "毎日ピアノを練習しています。",
    exampleVi: "Tôi luyện tập đàn piano mỗi ngày.",
    status: "mastered",
    lang: "ja",
    urgency: "ok",
    nextReview: "5 ngày nữa",
    reviewReason: "Nhớ tốt. LexiPath duy trì ôn nhẹ để giữ mức nhớ.",
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 92 },
      { skill: "listening",   label: "Nghe",           accuracy: 85 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 88 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 80 },
      { skill: "collocation", label: "Collocation",    accuracy: 74 },
    ],
  },
  {
    id: "ja-v8",
    word: "挑戦",
    reading: "ちょうせん",
    pos: "Danh từ · Động từ",
    meaning: "Thử thách, thách thức",
    example: "新しいことに挑戦するのは楽しいです。",
    exampleVi: "Thử thách những điều mới mẻ thật thú vị.",
    status: "learning",
    lang: "ja",
    urgency: "none",
    nextReview: "Ngày mai 15:00",
    reviewReason: "LexiPath đang theo dõi tiến trình của từ này.",
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 68 },
      { skill: "listening",   label: "Nghe",           accuracy: 60 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 72 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 50 },
      { skill: "collocation", label: "Collocation",    accuracy: 42 },
    ],
  },

  // ── English ──────────────────────────────────────────────────
  {
    id: "en-v1",
    word: "accomplish",
    reading: "/əˈkɒmplɪʃ/",
    pos: "Động từ",
    meaning: "Hoàn thành, đạt được (mục tiêu)",
    example: "She accomplished her goal of running a marathon.",
    exampleVi: "Cô ấy đã hoàn thành mục tiêu chạy marathon.",
    status: "review",
    lang: "en",
    urgency: "due",
    nextReview: "Hôm nay 17:00",
    reviewReason: "Kỹ năng Cách dùng còn thấp — đây là từ khó đặt câu đúng ngữ cảnh.",
    weakSkill: { skill: "usage", label: "Cách dùng", evidence: "Thường nhầm nghĩa với achieve/complete." },
    phrases: ["accomplish a goal", "accomplish a task", "accomplish nothing"],
    relatedWords: [
      { id: "en-rel1", word: "achieve" },
      { id: "en-rel2", word: "complete" },
      { id: "en-rel3", word: "fulfill" },
    ],
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 76 },
      { skill: "listening",   label: "Nghe",           accuracy: 68 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 80 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 58 },
      { skill: "collocation", label: "Collocation",    accuracy: 50 },
    ],
  },
  {
    id: "en-v2",
    word: "determine",
    reading: "/dɪˈtɜːrmɪn/",
    pos: "Động từ",
    meaning: "Xác định, quyết định",
    example: "Scientists are trying to determine the cause of the disease.",
    exampleVi: "Các nhà khoa học đang cố xác định nguyên nhân của căn bệnh.",
    status: "forgetting",
    lang: "en",
    urgency: "overdue",
    nextReview: "Quá hạn 1 ngày",
    reviewReason: "Bạn nghe nhầm /dɪˈtɜːrmɪn/ trong bài mock IELTS Listening gần nhất. LexiPath đã đẩy kỹ năng Nghe hiểu lên hàng chờ Golden Time.",
    weakSkill: { skill: "listening", label: "Nghe hiểu", evidence: "Nhầm /dɪˈtɜːrmɪn/ với /dɪˈtɜːrmaɪn/ khi nghe." },
    phrases: ["determine the cause", "determine whether", "determine the result"],
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 60 },
      { skill: "listening",   label: "Nghe",           accuracy: 52 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 66 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 42 },
      { skill: "collocation", label: "Collocation",    accuracy: 36 },
    ],
  },
  {
    id: "en-v3",
    word: "negotiate",
    reading: "/nɪˈɡəʊʃɪeɪt/",
    pos: "Động từ",
    meaning: "Đàm phán, thương lượng",
    example: "They negotiated a deal that benefited both sides.",
    exampleVi: "Họ đàm phán một thỏa thuận có lợi cho cả hai bên.",
    status: "learning",
    lang: "en",
    urgency: "none",
    nextReview: "Ngày mai 10:00",
    reviewReason: "LexiPath đang theo dõi tiến trình của từ này.",
    phrases: ["negotiate a deal", "negotiate terms", "negotiate with"],
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 72 },
      { skill: "listening",   label: "Nghe",           accuracy: 65 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 58 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 48 },
      { skill: "collocation", label: "Collocation",    accuracy: 40 },
    ],
  },
  {
    id: "en-v4",
    word: "revenue",
    reading: "/ˈrevənjuː/",
    pos: "Danh từ",
    meaning: "Doanh thu, thu nhập",
    example: "The company reported record revenue this quarter.",
    exampleVi: "Công ty báo cáo doanh thu kỷ lục trong quý này.",
    status: "mastered",
    lang: "en",
    urgency: "ok",
    nextReview: "7 ngày nữa",
    reviewReason: "Nhớ tốt. LexiPath duy trì ôn nhẹ để giữ mức nhớ.",
    phrases: ["revenue stream", "annual revenue", "revenue growth"],
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 94 },
      { skill: "listening",   label: "Nghe",           accuracy: 88 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 90 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 85 },
      { skill: "collocation", label: "Collocation",    accuracy: 80 },
    ],
  },
  {
    id: "en-v5",
    word: "significant",
    reading: "/sɪɡˈnɪfɪkənt/",
    pos: "Tính từ",
    meaning: "Đáng kể, có ý nghĩa",
    example: "There has been a significant improvement in his performance.",
    exampleVi: "Đã có sự cải thiện đáng kể trong kết quả của anh ấy.",
    status: "learning",
    lang: "en",
    urgency: "due",
    nextReview: "Hôm nay 19:00",
    reviewReason: "Golden Time đang đến hạn, ôn bây giờ sẽ giữ nhịp nhớ.",
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 65 },
      { skill: "listening",   label: "Nghe",           accuracy: 58 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 62 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 50 },
      { skill: "collocation", label: "Collocation",    accuracy: 44 },
    ],
  },
  {
    id: "en-v6",
    word: "establish",
    reading: "/ɪˈstæblɪʃ/",
    pos: "Động từ",
    meaning: "Thành lập, thiết lập",
    example: "The school was established in 1920.",
    exampleVi: "Ngôi trường được thành lập vào năm 1920.",
    status: "new",
    lang: "en",
    urgency: "none",
    reviewReason: "Từ mới trong lộ trình — bắt đầu học để LexiPath xếp Golden Time.",
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 25 },
      { skill: "listening",   label: "Nghe",           accuracy: 20 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 22 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 15 },
      { skill: "collocation", label: "Collocation",    accuracy: 12 },
    ],
  },

  // ── Chinese ──────────────────────────────────────────────────
  {
    id: "zh-v1",
    word: "学习",
    reading: "xué xí",
    pos: "Động từ · Danh từ",
    meaning: "Học tập, nghiên cứu",
    example: "我每天都努力学习汉语。",
    exampleVi: "Tôi cố gắng học tiếng Trung mỗi ngày.",
    status: "learning",
    lang: "zh",
    urgency: "due",
    nextReview: "Hôm nay 19:00",
    reviewReason: "Kỹ năng Nghe hiểu còn yếu — cần ôn thêm thanh điệu 学习.",
    weakSkill: { skill: "listening", label: "Nghe hiểu", evidence: "Cần ôn thêm thanh điệu 学习." },
    phrases: ["努力学习", "学习方法", "学习进步"],
    relatedWords: [
      { id: "zh-rel1", word: "学", reading: "xué", meaning: "Học" },
      { id: "zh-rel2", word: "练习", reading: "liàn xí", meaning: "Luyện tập" },
    ],
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 70 },
      { skill: "listening",   label: "Nghe",           accuracy: 55 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 60 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 40 },
      { skill: "collocation", label: "Collocation",    accuracy: 32 },
    ],
  },
  {
    id: "zh-v2",
    word: "工作",
    reading: "gōng zuò",
    pos: "Danh từ · Động từ",
    meaning: "Công việc, làm việc",
    example: "她在一家大公司工作。",
    exampleVi: "Cô ấy làm việc tại một công ty lớn.",
    status: "mastered",
    lang: "zh",
    urgency: "ok",
    nextReview: "5 ngày nữa",
    reviewReason: "Đã thành thạo. LexiPath theo dõi định kỳ để duy trì.",
    phrases: ["认真工作", "工作经验", "找工作"],
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 93 },
      { skill: "listening",   label: "Nghe",           accuracy: 86 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 88 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 82 },
      { skill: "collocation", label: "Collocation",    accuracy: 76 },
    ],
  },
  {
    id: "zh-v3",
    word: "朋友",
    reading: "péng you",
    pos: "Danh từ",
    meaning: "Bạn bè, bạn thân",
    example: "他是我最好的朋友。",
    exampleVi: "Anh ấy là người bạn thân nhất của tôi.",
    status: "review",
    lang: "zh",
    urgency: "due",
    nextReview: "Ngày mai 08:00",
    reviewReason: "Hay nhầm gōng (1) với góng (3) khi nghe — kỹ năng Nghe hiểu yếu.",
    weakSkill: { skill: "listening", label: "Thanh điệu", evidence: "Hay nhầm thanh điệu khi nghe nhanh." },
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 75 },
      { skill: "listening",   label: "Nghe",           accuracy: 60 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 68 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 55 },
      { skill: "collocation", label: "Collocation",    accuracy: 45 },
    ],
  },
  {
    id: "zh-v4",
    word: "经验",
    reading: "jīng yàn",
    pos: "Danh từ",
    meaning: "Kinh nghiệm",
    example: "他有丰富的工作经验。",
    exampleVi: "Anh ấy có kinh nghiệm làm việc phong phú.",
    status: "forgetting",
    lang: "zh",
    urgency: "overdue",
    nextReview: "Quá hạn 1 ngày",
    reviewReason: "Quá hạn 1 ngày — ôn ngay để không quên.",
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 48 },
      { skill: "listening",   label: "Nghe",           accuracy: 40 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 52 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 35 },
      { skill: "collocation", label: "Collocation",    accuracy: 30 },
    ],
  },
  {
    id: "zh-v5",
    word: "努力",
    reading: "nǔ lì",
    pos: "Động từ · Tính từ",
    meaning: "Nỗ lực, cố gắng",
    example: "只要努力，就一定能成功。",
    exampleVi: "Chỉ cần nỗ lực, nhất định sẽ thành công.",
    status: "new",
    lang: "zh",
    urgency: "none",
    reviewReason: "Từ mới — bắt đầu học để LexiPath xếp lịch ôn.",
    phrases: ["努力奋斗", "加油努力", "努力学习"],
    skills: [
      { skill: "meaning",     label: "Nghĩa",         accuracy: 28 },
      { skill: "listening",   label: "Nghe",           accuracy: 22 },
      { skill: "spelling",    label: "Chính tả",       accuracy: 25 },
      { skill: "usage",       label: "Cách dùng",      accuracy: 18 },
      { skill: "collocation", label: "Collocation",    accuracy: 15 },
    ],
  },
];
