import type {
  Entitlement,
  PaymentOrder,
  PaymentTransaction,
  RefundRecord,
  SubscriptionPlan,
  Subscription,
  WebhookEvent,
} from "./types";

export const MOCK_PLANS: SubscriptionPlan[] = [
  {
    id: "plan_free",
    code: "free",
    name: "Miễn phí",
    price: "0đ",
    interval: "—",
    status: "active",
    subscribers: 24830,
    features: ["3 bộ sưu tập", "10 từ/ngày", "Golden Time cơ bản"],
  },
  {
    id: "plan_plus",
    code: "plus_month",
    name: "Plus",
    price: "79.000đ",
    interval: "tháng",
    status: "active",
    subscribers: 1284,
    features: [
      "Không giới hạn",
      "Golden Time nâng cao",
      "Không quảng cáo",
      "Thống kê chi tiết",
    ],
  },
  {
    id: "plan_year",
    code: "plus_year",
    name: "Plus (năm)",
    price: "790.000đ",
    interval: "năm",
    status: "active",
    subscribers: 612,
    features: ["Toàn bộ Plus", "Tiết kiệm 2 tháng"],
  },
  {
    id: "plan_team",
    code: "team_month",
    name: "Team",
    price: "199.000đ",
    interval: "tháng",
    status: "active",
    subscribers: 96,
    features: [
      "Toàn bộ Plus",
      "Quản lý nhóm",
      "Bảng xếp hạng",
      "Admin dashboard",
    ],
  },
  {
    id: "plan_ent",
    code: "enterprise",
    name: "Enterprise",
    price: "Liên hệ",
    interval: "năm",
    status: "draft",
    subscribers: 0,
    features: ["Tùy chỉnh", "SSO", "SLA riêng", "API mở rộng"],
  },
];

export const MOCK_SUBSCRIPTIONS: Subscription[] = [
  {
    id: "sub_1",
    user: "Minh Anh",
    email: "minhanh@gmail.com",
    plan: "Plus",
    tier: "pro",
    status: "active",
    started: "01/05/2026",
    renews: "01/06/2026",
    amount: "79.000đ",
    method: "Momo",
  },
  {
    id: "sub_2",
    user: "Hoàng Lê",
    email: "hoangle@gmail.com",
    plan: "Plus (năm)",
    tier: "pro",
    status: "trialing",
    started: "05/06/2026",
    renews: "12/06/2026",
    amount: "790.000đ",
    method: "VNPay",
  },
  {
    id: "sub_3",
    user: "Secomus",
    email: "team@secomus.com",
    plan: "Team",
    tier: "team",
    status: "active",
    started: "08/03/2026",
    renews: "08/06/2026",
    amount: "199.000đ",
    method: "Chuyển khoản",
  },
  {
    id: "sub_4",
    user: "Thảo Nguyễn",
    email: "thaonguyen@gmail.com",
    plan: "Plus",
    tier: "pro",
    status: "past_due",
    started: "02/04/2026",
    renews: "02/06/2026",
    amount: "79.000đ",
    method: "Thẻ tín dụng",
  },
  {
    id: "sub_5",
    user: "Duy Phạm",
    email: "duypham@gmail.com",
    plan: "Plus",
    tier: "pro",
    status: "cancelled",
    started: "10/01/2026",
    renews: "—",
    amount: "79.000đ",
    method: "Momo",
  },
  {
    id: "sub_6",
    user: "Lan Hồ",
    email: "lan@gmail.com",
    plan: "Plus",
    tier: "pro",
    status: "expired",
    started: "20/12/2025",
    renews: "—",
    amount: "79.000đ",
    method: "VNPay",
  },
];

export const MOCK_ENTITLEMENTS: Record<string, Entitlement[]> = {
  sub_1: [
    {
      feature: "Bộ sưu tập không giới hạn",
      source: "plan",
      expires: "01/06/2026",
    },
    {
      feature: "Golden Time nâng cao",
      source: "plan",
      expires: "01/06/2026",
    },
    { feature: "Thống kê chi tiết", source: "plan", expires: "01/06/2026" },
    { feature: "Hỗ trợ ưu tiên", source: "grant", expires: "31/12/2026" },
  ],
  sub_2: [
    {
      feature: "Bộ sưu tập không giới hạn",
      source: "plan",
      expires: "12/06/2026",
    },
    {
      feature: "Golden Time nâng cao",
      source: "plan",
      expires: "12/06/2026",
    },
  ],
  sub_3: [
    {
      feature: "Quản lý nhóm",
      source: "plan",
      expires: "08/06/2026",
    },
    {
      feature: "Bảng xếp hạng",
      source: "plan",
      expires: "08/06/2026",
    },
    {
      feature: "Admin dashboard",
      source: "plan",
      expires: "08/06/2026",
    },
  ],
};

export const MOCK_ORDERS: PaymentOrder[] = [
  {
    id: "ord_1",
    code: "ORD-20260609-1284",
    user: "Minh Anh",
    email: "minhanh@gmail.com",
    item: "Plus — 1 tháng",
    amount: "79.000đ",
    status: "success",
    method: "Momo",
    created: "09/06/2026 09:12",
  },
  {
    id: "ord_2",
    code: "ORD-20260609-1285",
    user: "Hoàng Lê",
    email: "hoangle@gmail.com",
    item: "Plus (năm)",
    amount: "790.000đ",
    status: "pending",
    method: "VNPay",
    created: "09/06/2026 08:40",
  },
  {
    id: "ord_3",
    code: "ORD-20260608-1280",
    user: "Secomus",
    email: "team@secomus.com",
    item: "Team — 10 ghế",
    amount: "199.000đ",
    status: "success",
    method: "Chuyển khoản",
    created: "08/06/2026 16:05",
  },
  {
    id: "ord_4",
    code: "ORD-20260607-1271",
    user: "Thảo Nguyễn",
    email: "thaonguyen@gmail.com",
    item: "Plus — 1 tháng",
    amount: "79.000đ",
    status: "failed",
    method: "Thẻ tín dụng",
    created: "07/06/2026 21:18",
  },
  {
    id: "ord_5",
    code: "ORD-20260606-1264",
    user: "Duy Phạm",
    email: "duypham@gmail.com",
    item: "Plus — 1 tháng",
    amount: "79.000đ",
    status: "refunded",
    method: "Momo",
    created: "06/06/2026 11:02",
  },
];

export const MOCK_TRANSACTIONS: Record<string, PaymentTransaction[]> = {
  ord_1: [
    {
      id: "txn_1a",
      code: "TXN-9f23a1",
      type: "Thanh toán",
      gateway: "Momo",
      gatewayRef: "MOMO-2026060912001",
      amount: "79.000đ",
      status: "success",
      at: "09/06/2026 09:12:04",
    },
  ],
  ord_2: [
    {
      id: "txn_2a",
      code: "TXN-7c81b4",
      type: "Tạo lệnh",
      gateway: "VNPay",
      gatewayRef: "VNP-88210045",
      amount: "790.000đ",
      status: "pending",
      at: "09/06/2026 08:40:11",
    },
  ],
  ord_3: [
    {
      id: "txn_3a",
      code: "TXN-2e44c0",
      type: "Thanh toán",
      gateway: "Chuyển khoản",
      gatewayRef: "CK-20260608-1280",
      amount: "199.000đ",
      status: "success",
      at: "08/06/2026 16:05:22",
    },
  ],
  ord_4: [
    {
      id: "txn_4a",
      code: "TXN-1d50f9",
      type: "Thanh toán",
      gateway: "Stripe",
      gatewayRef: "ch_3Pd…fail",
      amount: "79.000đ",
      status: "failed",
      at: "07/06/2026 21:18:33",
    },
    {
      id: "txn_4b",
      code: "TXN-1d50fa",
      type: "Thử lại",
      gateway: "Stripe",
      gatewayRef: "ch_3Pe…fail",
      amount: "79.000đ",
      status: "failed",
      at: "07/06/2026 21:20:01",
    },
  ],
  ord_5: [
    {
      id: "txn_5a",
      code: "TXN-44ab02",
      type: "Thanh toán",
      gateway: "Momo",
      gatewayRef: "MOMO-2026060611005",
      amount: "79.000đ",
      status: "success",
      at: "06/06/2026 11:02:51",
    },
    {
      id: "txn_5b",
      code: "TXN-44ab9c",
      type: "Hoàn tiền",
      gateway: "Momo",
      gatewayRef: "MOMO-RF-77120",
      amount: "-79.000đ",
      status: "refunded",
      at: "07/06/2026 10:14:20",
    },
  ],
};

export const MOCK_WEBHOOKS: WebhookEvent[] = [
  {
    id: "wh_1",
    event: "payment.succeeded",
    provider: "Momo",
    status: "processed",
    received: "09/06/2026 09:12:06",
    attempts: 1,
    ref: "ORD-20260609-1284",
  },
  {
    id: "wh_2",
    event: "order.created",
    provider: "VNPay",
    status: "processed",
    received: "09/06/2026 08:40:13",
    attempts: 1,
    ref: "ORD-20260609-1285",
  },
  {
    id: "wh_3",
    event: "payment.failed",
    provider: "Stripe",
    status: "processed",
    received: "07/06/2026 21:18:35",
    attempts: 1,
    ref: "ORD-20260607-1271",
  },
  {
    id: "wh_4",
    event: "refund.completed",
    provider: "Momo",
    status: "failed",
    received: "07/06/2026 10:14:22",
    attempts: 4,
    ref: "ORD-20260606-1264",
  },
  {
    id: "wh_5",
    event: "subscription.renewed",
    provider: "VNPay",
    status: "received",
    received: "09/06/2026 09:30:00",
    attempts: 0,
    ref: "sub_2",
  },
];

export const WEBHOOK_PAYLOAD = `{
  "id": "evt_4Ab92x",
  "type": "refund.completed",
  "provider": "momo",
  "created": "2026-06-07T10:14:22+07:00",
  "data": {
    "orderId": "ORD-20260606-1264",
    "refundId": "MOMO-RF-77120",
    "amount": 79000,
    "currency": "VND",
    "status": "completed"
  }
}`;

export const MOCK_REFUNDS: RefundRecord[] = [
  {
    id: "rf_1",
    code: "RF-1042",
    user: "Duy Phạm",
    email: "duypham@gmail.com",
    order: "ORD-20260606-1264",
    amount: "79.000đ",
    reason: "Đăng ký nhầm gói",
    status: "processed",
    requested: "07/06/2026",
    by: "Duy Phạm",
  },
  {
    id: "rf_2",
    code: "RF-1043",
    user: "Thảo Nguyễn",
    email: "thaonguyen@gmail.com",
    order: "ORD-20260607-1271",
    amount: "79.000đ",
    reason: "Thanh toán hai lần",
    status: "requested",
    requested: "09/06/2026",
    by: "Hỗ trợ",
  },
  {
    id: "rf_3",
    code: "RF-1044",
    user: "Lan Hồ",
    email: "lan@gmail.com",
    order: "ORD-20260520-1180",
    amount: "790.000đ",
    reason: "Không hài lòng dịch vụ",
    status: "requested",
    requested: "08/06/2026",
    by: "Lan Hồ",
  },
  {
    id: "rf_4",
    code: "RF-1041",
    user: "Khánh Trần",
    email: "khanh@gmail.com",
    order: "ORD-20260512-1102",
    amount: "199.000đ",
    reason: "Lỗi tính phí",
    status: "approved",
    requested: "06/06/2026",
    by: "Hỗ trợ",
  },
  {
    id: "rf_5",
    code: "RF-1039",
    user: "An Nguyễn",
    email: "an@gmail.com",
    order: "ORD-20260430-0921",
    amount: "79.000đ",
    reason: "Yêu cầu ngoài chính sách",
    status: "rejected",
    requested: "02/06/2026",
    by: "Hỗ trợ",
  },
];
