import type {
  LearnerExamProgram,
  LearnerExamTest,
  ExamTypeMeta,
  ExamBlueprintsMap,
} from './types';

export const EXAM_PROGRAMS: LearnerExamProgram[] = [
  {
    id: 'ielts',
    name: 'IELTS',
    fullName: 'International English Language Testing System',
    lang: 'en',
    langFlag: '🇬🇧',
    color: '#2563EB',
    colorSoft: '#EFF6FF',
    colorSoftFg: '#1d4ed8',
    glyphBig: 'IE',
    desc: 'Chứng chỉ tiếng Anh quốc tế được công nhận toàn cầu — học thuật, di cư và làm việc.',
    levels: ['Band 5.0', 'Band 5.5', 'Band 6.0', 'Band 6.5', 'Band 7.0', 'Band 7.5+'],
    testCount: 6,
    freeCount: 3,
    skills: ['Nghe', 'Đọc', 'Viết', 'Nói'],
    featured: true,
  },
  {
    id: 'toeic',
    name: 'TOEIC',
    fullName: 'Test of English for International Communication',
    lang: 'en',
    langFlag: '🇬🇧',
    color: '#0284C7',
    colorSoft: '#F0F9FF',
    colorSoftFg: '#0369a1',
    glyphBig: 'TO',
    desc: 'Đánh giá năng lực tiếng Anh giao tiếp trong môi trường làm việc quốc tế.',
    levels: ['450', '600', '730', '860', '990'],
    testCount: 7,
    freeCount: 4,
    skills: ['Nghe', 'Đọc'],
    featured: true,
  },
  {
    id: 'hsk',
    name: 'HSK',
    fullName: '汉语水平考试 — Hán ngữ Thủy Bình Khảo Thí',
    lang: 'zh',
    langFlag: '🇨🇳',
    color: '#DC2626',
    colorSoft: '#FEF2F2',
    colorSoftFg: '#b91c1c',
    glyphBig: '汉',
    desc: 'Kỳ thi năng lực tiếng Trung Quốc chuẩn quốc tế, được công nhận bởi Hanban.',
    levels: ['HSK 1', 'HSK 2', 'HSK 3', 'HSK 4', 'HSK 5', 'HSK 6'],
    testCount: 4,
    freeCount: 2,
    skills: ['Nghe', 'Đọc', 'Viết'],
    featured: false,
  },
  {
    id: 'jlpt',
    name: 'JLPT',
    fullName: '日本語能力試験 — Kỳ thi Năng lực Tiếng Nhật',
    lang: 'ja',
    langFlag: '🇯🇵',
    color: '#7C3AED',
    colorSoft: '#F5F3FF',
    colorSoftFg: '#6d28d9',
    glyphBig: '日',
    desc: 'Kỳ thi tiêu chuẩn đánh giá năng lực tiếng Nhật cho người không phải bản ngữ.',
    levels: ['N5', 'N4', 'N3', 'N2', 'N1'],
    testCount: 4,
    freeCount: 3,
    skills: ['Ngôn ngữ', 'Đọc hiểu', 'Nghe hiểu'],
    featured: false,
  },
];

export const EXAM_TYPE_META: ExamTypeMeta = {
  full:     { label: 'Đề đầy đủ',    icon: 'FileText', color: '#2563EB', soft: '#EFF6FF', softFg: '#1d4ed8' },
  mini:     { label: 'Đề mini',       icon: 'Zap',      color: '#D97706', soft: '#FFFBEB', softFg: '#92400e' },
  skill:    { label: 'Luyện kỹ năng', icon: 'Target',   color: '#059669', soft: '#ECFDF5', softFg: '#065f46' },
  practice: { label: 'Bộ luyện tập', icon: 'RefreshCw', color: '#7C3AED', soft: '#F5F3FF', softFg: '#5b21b6' },
};

export const EXAM_TESTS: LearnerExamTest[] = [
  /* IELTS */
  { id: 'ielts-ac-1', programId: 'ielts', typeId: 'full',
    title: 'IELTS Academic — Đề thực hành 1', level: 'Band 6.0–7.0',
    durationMin: 165, questions: 80, maxScore: 'Band 9', access: 'free', featured: true, isNew: false,
    skills: ['Nghe', 'Đọc', 'Viết', 'Nói'],
    desc: 'Mô phỏng 4 kỹ năng y hệt kỳ thi thật. Phù hợp với người học mục tiêu band 6–7.' },
  { id: 'ielts-ac-2', programId: 'ielts', typeId: 'full',
    title: 'IELTS Academic — Đề thực hành 2', level: 'Band 6.5–7.5',
    durationMin: 165, questions: 80, maxScore: 'Band 9', access: 'pro', featured: false, isNew: false,
    skills: ['Nghe', 'Đọc', 'Viết', 'Nói'],
    desc: 'Đề khó hơn — dành cho người học mục tiêu band 6.5 trở lên.' },
  { id: 'ielts-gt-1', programId: 'ielts', typeId: 'full',
    title: 'IELTS General Training — Đề 1', level: 'Band 5.5–6.5',
    durationMin: 165, questions: 80, maxScore: 'Band 9', access: 'pro', featured: false, isNew: true,
    skills: ['Nghe', 'Đọc', 'Viết', 'Nói'],
    desc: 'Module General Training cho mục đích định cư, làm việc tại các nước Anh ngữ.' },
  { id: 'ielts-listen-1', programId: 'ielts', typeId: 'skill',
    title: 'Luyện nghe IELTS — Section 1 & 2', level: 'Band 5.0–6.0',
    durationMin: 30, questions: 20, maxScore: '20 điểm', access: 'free', featured: false, isNew: false,
    skills: ['Nghe'],
    desc: 'Tập trung 2 section nghe dễ nhất: hội thoại thực tế và độc thoại.' },
  { id: 'ielts-read-1', programId: 'ielts', typeId: 'skill',
    title: 'Luyện đọc IELTS Academic', level: 'Band 6.0–7.0',
    durationMin: 60, questions: 40, maxScore: '40 điểm', access: 'free', featured: false, isNew: true,
    skills: ['Đọc'],
    desc: '3 passage học thuật đầy đủ — luyện tốc độ đọc và True/False/NG.' },
  { id: 'ielts-mini-1', programId: 'ielts', typeId: 'mini',
    title: 'IELTS Mini Test — Mục tiêu Band 6', level: 'Band 5.5–6.5',
    durationMin: 45, questions: 30, maxScore: 'Band 9', access: 'free', featured: true, isNew: false,
    skills: ['Nghe', 'Đọc'],
    desc: 'Chỉ 45 phút — chọn lọc câu hỏi đại diện nhất từ Nghe và Đọc.' },

  /* TOEIC */
  { id: 'toeic-lr-1', programId: 'toeic', typeId: 'full',
    title: 'TOEIC L&R — Đề mô phỏng 1', level: 'Mục tiêu 600',
    durationMin: 120, questions: 200, maxScore: '990 điểm', access: 'free', featured: true, isNew: false,
    skills: ['Nghe', 'Đọc'],
    desc: '200 câu theo chuẩn ETS — Part 1–7 đầy đủ, thời gian và cách tính điểm y hệt thi thật.' },
  { id: 'toeic-lr-2', programId: 'toeic', typeId: 'full',
    title: 'TOEIC L&R — Đề mô phỏng 2', level: 'Mục tiêu 730',
    durationMin: 120, questions: 200, maxScore: '990 điểm', access: 'pro', featured: false, isNew: false,
    skills: ['Nghe', 'Đọc'],
    desc: 'Độ khó trung bình-cao, luyện Part 3–4 và Part 7 dài.' },
  { id: 'toeic-lr-3', programId: 'toeic', typeId: 'full',
    title: 'TOEIC L&R — Đề mô phỏng 3', level: 'Mục tiêu 860',
    durationMin: 120, questions: 200, maxScore: '990 điểm', access: 'pro', featured: false, isNew: true,
    skills: ['Nghe', 'Đọc'],
    desc: 'Đề khó nhất — cho người học mục tiêu 860+ điểm.' },
  { id: 'toeic-part5', programId: 'toeic', typeId: 'skill',
    title: 'Luyện tập Part 5 — Ngữ pháp & Từ vựng', level: '450–730',
    durationMin: 25, questions: 30, maxScore: '30 điểm', access: 'free', featured: false, isNew: false,
    skills: ['Đọc'],
    desc: '30 câu Part 5 tập trung ngữ pháp và từ vựng hay gặp nhất.' },
  { id: 'toeic-part1-2', programId: 'toeic', typeId: 'skill',
    title: 'Luyện nghe Part 1 & 2', level: '450–600',
    durationMin: 20, questions: 32, maxScore: '32 điểm', access: 'free', featured: false, isNew: true,
    skills: ['Nghe'],
    desc: 'Mô tả hình ảnh và câu hỏi-đáp — 2 phần nghe nền tảng nhất.' },
  { id: 'toeic-mini-600', programId: 'toeic', typeId: 'mini',
    title: 'TOEIC Mini — Mục tiêu 600', level: '450–600',
    durationMin: 50, questions: 60, maxScore: '990 điểm', access: 'free', featured: true, isNew: false,
    skills: ['Nghe', 'Đọc'],
    desc: 'Chỉ 50 phút — 60 câu đại diện cho cả Nghe và Đọc.' },
  { id: 'toeic-vocab-1', programId: 'toeic', typeId: 'practice',
    title: 'Từ vựng TOEIC theo chủ đề', level: '450–730',
    durationMin: 15, questions: 40, maxScore: '40 điểm', access: 'free', featured: false, isNew: false,
    skills: ['Đọc'],
    desc: '40 câu từ vựng theo 2 chủ đề trọng tâm: văn phòng và tài chính.' },

  /* HSK */
  { id: 'hsk3-1', programId: 'hsk', typeId: 'full',
    title: 'HSK 3 — Đề thực hành 1', level: 'HSK 3',
    durationMin: 85, questions: 100, maxScore: '300 điểm', access: 'free', featured: true, isNew: false,
    skills: ['Nghe', 'Đọc', 'Viết'],
    desc: '3 phần Nghe-Đọc-Viết đầy đủ theo đúng cấu trúc kỳ thi Hanban.' },
  { id: 'hsk4-1', programId: 'hsk', typeId: 'full',
    title: 'HSK 4 — Đề thực hành 1', level: 'HSK 4',
    durationMin: 100, questions: 100, maxScore: '300 điểm', access: 'pro', featured: false, isNew: false,
    skills: ['Nghe', 'Đọc', 'Viết'],
    desc: 'Cấp độ cao hơn — từ vựng HSK 4 (khoảng 1200 từ).' },
  { id: 'hsk3-mini', programId: 'hsk', typeId: 'mini',
    title: 'HSK 3 Mini — Nghe & Đọc', level: 'HSK 3',
    durationMin: 40, questions: 50, maxScore: '150 điểm', access: 'free', featured: false, isNew: true,
    skills: ['Nghe', 'Đọc'],
    desc: 'Rút gọn phần Nghe và Đọc — không cần viết chữ Hán.' },
  { id: 'hsk-listen-1', programId: 'hsk', typeId: 'skill',
    title: 'Luyện nghe HSK 3', level: 'HSK 3',
    durationMin: 20, questions: 20, maxScore: '20 điểm', access: 'free', featured: false, isNew: false,
    skills: ['Nghe'],
    desc: '4 dạng câu hỏi nghe chuẩn HSK 3.' },

  /* JLPT */
  { id: 'jlpt-n4-1', programId: 'jlpt', typeId: 'full',
    title: 'JLPT N4 — Đề thực hành 1', level: 'N4',
    durationMin: 105, questions: 80, maxScore: '180 điểm', access: 'free', featured: true, isNew: false,
    skills: ['Ngôn ngữ', 'Đọc hiểu', 'Nghe hiểu'],
    desc: '3 phần đầy đủ — cấu trúc đúng kỳ thi chính thức JLPT N4.' },
  { id: 'jlpt-n5-1', programId: 'jlpt', typeId: 'full',
    title: 'JLPT N5 — Đề thực hành 1', level: 'N5',
    durationMin: 75, questions: 67, maxScore: '180 điểm', access: 'free', featured: false, isNew: false,
    skills: ['Ngôn ngữ', 'Đọc hiểu', 'Nghe hiểu'],
    desc: 'Đề N5 cơ bản — khởi đầu lý tưởng cho người mới học tiếng Nhật.' },
  { id: 'jlpt-n4-mini', programId: 'jlpt', typeId: 'mini',
    title: 'JLPT N4 Mini — Ngữ pháp', level: 'N4',
    durationMin: 20, questions: 20, maxScore: '60 điểm', access: 'free', featured: false, isNew: true,
    skills: ['Ngôn ngữ'],
    desc: 'Tập trung ngữ pháp N4 — cấu trúc câu và điền từ vào đoạn văn.' },
  { id: 'jlpt-vocab-n4', programId: 'jlpt', typeId: 'practice',
    title: 'Luyện từ vựng JLPT N4', level: 'N4',
    durationMin: 20, questions: 30, maxScore: '60 điểm', access: 'free', featured: false, isNew: false,
    skills: ['Ngôn ngữ'],
    desc: 'Đọc chữ Kanji và nghĩa từ vựng trọng tâm N4.' },
];

export const EXAM_BLUEPRINTS: ExamBlueprintsMap = {
  'ielts-ac-1': {
    description: 'Đề IELTS Academic mô phỏng cấu trúc thi thật — 4 kỹ năng, thời gian và số câu hỏi đúng như kỳ thi chính thức. Phù hợp với người học mục tiêu band 6.0–7.0.',
    instruction: 'Làm bài theo đúng thứ tự: Nghe → Đọc → Viết. Phần Nói được lên lịch riêng. Không có thời gian bổ sung sau khi hết giờ.',
    scoreSystem: 'Band 0.0–9.0 (bước 0.5). Điểm tổng = trung bình cộng 4 kỹ năng, làm tròn đến 0.5 gần nhất.',
    passMark: 'Band 6.0 (học thuật / visa)',
    accessLocked: false,
    relatedCollections: [
      { id: 'ielts-vocab', title: 'IELTS Academic Vocabulary', items: 500, collId: 'en-toeic-600' },
      { id: 'ielts-colls', title: 'IELTS Collocations & Phrases', items: 200, collId: 'en-toeic-600' },
    ],
    sections: [
      { name: 'Nghe (Listening)', durationMin: 30, totalQ: 40, parts: [
        { name: 'Section 1', desc: 'Hội thoại trong tình huống thực tế (2 người)', q: 10, type: 'Điền chỗ trống, trắc nghiệm' },
        { name: 'Section 2', desc: 'Độc thoại về chủ đề thực tế (1 người nói)', q: 10, type: 'Trắc nghiệm, sơ đồ/bản đồ' },
        { name: 'Section 3', desc: 'Hội thoại học thuật (2–4 người)', q: 10, type: 'Trắc nghiệm, phân loại' },
        { name: 'Section 4', desc: 'Bài giảng / nói chuyện học thuật', q: 10, type: 'Điền chỗ trống' },
      ]},
      { name: 'Đọc (Reading)', durationMin: 60, totalQ: 40, parts: [
        { name: 'Passage 1', desc: 'Văn bản học thuật ~800 từ', q: 13, type: 'True/False/Not Given, điền tiêu đề' },
        { name: 'Passage 2', desc: 'Văn bản học thuật ~900 từ', q: 13, type: 'Trắc nghiệm, điền chỗ trống' },
        { name: 'Passage 3', desc: 'Văn bản học thuật ~1000 từ (khó nhất)', q: 14, type: 'Ghép đầu đề, điền bảng' },
      ]},
      { name: 'Viết (Writing)', durationMin: 60, totalQ: 2, parts: [
        { name: 'Task 1', desc: 'Mô tả biểu đồ / sơ đồ / bản đồ (≥150 từ)', q: 1, type: 'Bài viết tự do' },
        { name: 'Task 2', desc: 'Luận điểm / Vấn đề-Giải pháp (≥250 từ)', q: 1, type: 'Bài viết tự do' },
      ]},
      { name: 'Nói (Speaking)', durationMin: 15, totalQ: 10, parts: [
        { name: 'Part 1', desc: 'Giới thiệu bản thân và các chủ đề quen thuộc', q: 4, type: 'Phỏng vấn trực tiếp' },
        { name: 'Part 2', desc: 'Thuyết trình 1–2 phút về một chủ đề', q: 1, type: 'Độc thoại có chuẩn bị' },
        { name: 'Part 3', desc: 'Thảo luận chuyên sâu liên quan đến Part 2', q: 5, type: 'Phỏng vấn trực tiếp' },
      ]},
    ],
  },
  'toeic-lr-1': {
    description: 'Đề TOEIC L&R mô phỏng chuẩn ETS — 200 câu trắc nghiệm, cấu trúc và thời gian y hệt kỳ thi thật. Phù hợp mục tiêu 600 điểm.',
    instruction: 'Nghe (Part 1–4, 45 phút) trước, sau đó Đọc (Part 5–7, 75 phút). Hai phần tính điểm độc lập rồi cộng lại.',
    scoreSystem: 'Thang 10–990: Nghe (5–495) + Đọc (5–495). Quy đổi theo bảng điểm ETS chuẩn.',
    passMark: '600+ (môi trường công sở quốc tế)',
    accessLocked: false,
    relatedCollections: [
      { id: 'toeic-600', title: 'TOEIC 600 Essential Words', items: 600, collId: 'en-toeic-600' },
      { id: 'biz-phrases', title: 'Business English Phrases', items: 150, collId: 'en-toeic-600' },
    ],
    sections: [
      { name: 'Nghe (Listening)', durationMin: 45, totalQ: 100, parts: [
        { name: 'Part 1', desc: 'Mô tả hình ảnh', q: 6, type: '4 lựa chọn' },
        { name: 'Part 2', desc: 'Hỏi và đáp', q: 25, type: '3 lựa chọn' },
        { name: 'Part 3', desc: 'Đoạn hội thoại ngắn (2–3 người)', q: 39, type: 'Câu hỏi về hội thoại' },
        { name: 'Part 4', desc: 'Bài nói đơn (monologue)', q: 30, type: 'Câu hỏi về bài nói' },
      ]},
      { name: 'Đọc (Reading)', durationMin: 75, totalQ: 100, parts: [
        { name: 'Part 5', desc: 'Câu hoàn chỉnh — chọn từ đúng', q: 30, type: '4 lựa chọn' },
        { name: 'Part 6', desc: 'Điền vào đoạn văn', q: 16, type: '4 lựa chọn' },
        { name: 'Part 7', desc: 'Đọc hiểu đơn và đôi văn bản', q: 54, type: 'Trắc nghiệm' },
      ]},
    ],
  },
  'hsk3-1': {
    description: 'Đề HSK 3 mô phỏng đầy đủ — 3 phần Nghe-Đọc-Viết theo đúng cấu trúc kỳ thi Hanban. Dành cho người đã học khoảng 600 từ tiếng Trung.',
    instruction: 'Nghe (35 phút) → Đọc (30 phút) → Viết (20 phút). Tổng 85 phút. Phần Viết yêu cầu viết chữ Hán tay.',
    scoreSystem: 'Tổng 300 điểm: Nghe (100) + Đọc (100) + Viết (100). Đạt khi mỗi phần ≥60 điểm.',
    passMark: '180/300 điểm (60 mỗi phần)',
    accessLocked: false,
    relatedCollections: [
      { id: 'hsk3-vocab', title: 'HSK 3 Vocabulary (600 từ)', items: 600, collId: 'zh-hsk1' },
    ],
    sections: [
      { name: 'Nghe (听力)', durationMin: 35, totalQ: 40, parts: [
        { name: 'Phần 1', desc: 'Nghe câu ngắn, chọn hình mô tả đúng', q: 10, type: 'Chọn hình' },
        { name: 'Phần 2', desc: 'Nghe hội thoại, phán đoán Đúng/Sai', q: 10, type: 'Đúng/Sai' },
        { name: 'Phần 3', desc: 'Nghe hội thoại ngắn, trả lời câu hỏi', q: 10, type: '4 lựa chọn' },
        { name: 'Phần 4', desc: 'Nghe đoạn độc thoại, trả lời câu hỏi', q: 10, type: '4 lựa chọn' },
      ]},
      { name: 'Đọc (阅读)', durationMin: 30, totalQ: 30, parts: [
        { name: 'Phần 1', desc: 'Ghép câu với nghĩa phù hợp', q: 10, type: 'Ghép đôi' },
        { name: 'Phần 2', desc: 'Chọn từ điền vào chỗ trống', q: 10, type: '4 lựa chọn' },
        { name: 'Phần 3', desc: 'Đọc đoạn văn ngắn, trả lời câu hỏi', q: 10, type: '4 lựa chọn' },
      ]},
      { name: 'Viết (书写)', durationMin: 20, totalQ: 30, parts: [
        { name: 'Phần 1', desc: 'Sắp xếp lại từ thành câu đúng', q: 10, type: 'Sắp xếp từ' },
        { name: 'Phần 2', desc: 'Viết từ pinyin thành chữ Hán', q: 10, type: 'Chép chữ' },
        { name: 'Phần 3', desc: 'Viết chữ Hán từ gợi ý hình vẽ', q: 10, type: 'Viết chữ' },
      ]},
    ],
  },
  'jlpt-n4-1': {
    description: 'Đề JLPT N4 thực hành đầy đủ — 3 phần Ngôn ngữ-Ngữ pháp, Đọc hiểu, Nghe hiểu. Cấu trúc và thang điểm đúng kỳ thi chính thức.',
    instruction: 'Ngôn ngữ & Đọc hiểu làm liên tiếp (75 phút). Nghe hiểu (35 phút) làm sau cùng.',
    scoreSystem: 'Tổng 180 điểm: Ngôn ngữ-Ngữ pháp (60) + Đọc hiểu (60) + Nghe hiểu (60). Cần ≥90 tổng và đạt điểm sàn từng phần.',
    passMark: '90/180 điểm + điểm sàn từng phần',
    accessLocked: false,
    relatedCollections: [
      { id: 'jlpt-n4-v', title: 'JLPT N4 Vocabulary', items: 600, collId: 'ja-jlpt-n5' },
      { id: 'kanji-n4', title: 'Kanji N4', items: 170, collId: 'ja-jlpt-n5' },
    ],
    sections: [
      { name: 'Ngôn ngữ & Ngữ pháp', durationMin: 30, totalQ: 35, parts: [
        { name: 'Cách đọc chữ', desc: 'Chọn cách đọc đúng của từ được gạch chân', q: 9, type: '4 lựa chọn' },
        { name: 'Chính tả', desc: 'Chọn chữ viết đúng từ kana đã cho', q: 6, type: '4 lựa chọn' },
        { name: 'Ý nghĩa từ', desc: 'Chọn từ có ý nghĩa gần nhất', q: 10, type: '4 lựa chọn' },
        { name: 'Ngữ pháp', desc: 'Chọn cấu trúc ngữ pháp phù hợp', q: 10, type: '4 lựa chọn' },
      ]},
      { name: 'Đọc hiểu', durationMin: 45, totalQ: 10, parts: [
        { name: 'Đoạn văn ngắn', desc: 'Đọc và trả lời về đoạn văn 100–150 từ', q: 4, type: '4 lựa chọn' },
        { name: 'Đoạn văn dài', desc: 'Đọc và trả lời về đoạn văn ~300 từ', q: 4, type: '4 lựa chọn' },
        { name: 'Thông tin', desc: 'Đọc thông báo, biển hiệu và trả lời', q: 2, type: '4 lựa chọn' },
      ]},
      { name: 'Nghe hiểu', durationMin: 30, totalQ: 35, parts: [
        { name: 'Xử lý tình huống', desc: 'Nghe hội thoại, chọn hành động phù hợp', q: 8, type: '4 lựa chọn + hình' },
        { name: 'Hiểu trọng tâm', desc: 'Nghe hội thoại, trả lời câu hỏi', q: 7, type: '4 lựa chọn' },
        { name: 'Biểu đạt', desc: 'Nghe tình huống, chọn phản hồi đúng', q: 10, type: '3 lựa chọn' },
        { name: 'Biểu đạt nhanh', desc: 'Nghe ngắn, chọn phản hồi tức thì', q: 10, type: '3 lựa chọn' },
      ]},
    ],
  },
};
