import type {
  ReviewBoardTask,
  ReviewTaskDetail,
} from "./types";

export const REVIEW_TASKS_MOCK: ReviewBoardTask[] = [
  {
    id: "rt1",
    itemTitle: "accomplish",
    itemType: "word",
    lang: "en",
    author: "Minh Anh",
    assignee: "Thảo Nguyễn",
    status: "pending",
    priority: "high",
    created: "10/06/2026",
    updated: "11/06/2026",
    commentCount: 3,
    changeCount: 5,
  },
  {
    id: "rt2",
    itemTitle: "勉強",
    itemType: "kanji",
    lang: "ja",
    author: "Duy Phạm",
    assignee: "Thảo Nguyễn",
    status: "pending",
    priority: "medium",
    created: "10/06/2026",
    updated: "10/06/2026",
    commentCount: 1,
    changeCount: 2,
  },
  {
    id: "rt3",
    itemTitle: "学习",
    itemType: "word",
    lang: "zh",
    author: "Duy Phạm",
    assignee: "Minh Anh",
    status: "changes_requested",
    priority: "high",
    created: "09/06/2026",
    updated: "11/06/2026",
    commentCount: 4,
    changeCount: 7,
  },
  {
    id: "rt4",
    itemTitle: "negotiate",
    itemType: "word",
    lang: "en",
    author: "Thảo Nguyễn",
    assignee: "Minh Anh",
    status: "approved",
    priority: "low",
    created: "08/06/2026",
    updated: "10/06/2026",
    commentCount: 2,
    changeCount: 3,
  },
  {
    id: "rt5",
    itemTitle: "revenue",
    itemType: "word",
    lang: "en",
    author: "Thảo Nguyễn",
    assignee: "Minh Anh",
    status: "approved",
    priority: "medium",
    created: "07/06/2026",
    updated: "09/06/2026",
    commentCount: 1,
    changeCount: 1,
  },
  {
    id: "rt6",
    itemTitle: "約束",
    itemType: "word",
    lang: "ja",
    author: "Minh Anh",
    assignee: "Duy Phạm",
    status: "rejected",
    priority: "medium",
    created: "06/06/2026",
    updated: "08/06/2026",
    commentCount: 3,
    changeCount: 4,
  },
];

export const REVIEW_TASK_DETAILS_MOCK: Record<string, ReviewTaskDetail> = {
  rt1: {
    taskId: "rt1",
    item: { title: "accomplish", lang: "en", type: "word", contentStatus: "draft" },
    authorName: "Minh Anh",
    assigneeName: "Thảo Nguyễn",
    priority: "high",
    status: "pending",
    created: "10/06/2026 08:00",
    updated: "11/06/2026",
    changeCount: 5,
    diff: [
      {
        field: "en_collocations",
        before: "accomplish a goal, accomplish a mission",
        after: "accomplish a goal, accomplish a mission, accomplish a task, accomplish nothing",
      },
      {
        field: "senses[1].example",
        before: "(trống)",
        after: "Her accomplishments speak for themselves.",
      },
      {
        field: "en_ipa",
        before: "/əˈkɑːmplɪʃ/",
        after: "/əˈkɑːmplɪʃ/",
      },
    ],
    comments: [
      {
        id: "c1",
        author: "Minh Anh",
        role: "author",
        text: "Đã thêm IPA /əˈkɑːmplɪʃ/, audio US/UK, 2 ví dụ và 3 collocations. Scripts + phonetics đầy đủ.",
        timestamp: "10/06/2026 08:00",
        resolved: false,
      },
      {
        id: "c2",
        author: "Thảo Nguyễn",
        role: "reviewer",
        text: "IPA và audio ổn. Thiếu ví dụ cho nghĩa 2 (danh từ — achievement). Đề xuất thêm 2–3 collocation nữa: 'accomplish a task', 'accomplish nothing'.",
        timestamp: "10/06/2026 11:30",
        resolved: false,
        field: "Ví dụ",
        severity: "major",
      },
      {
        id: "c3",
        author: "Minh Anh",
        role: "author",
        text: "Đã cập nhật nghĩa 2 và bổ sung collocation. Mời duyệt lại.",
        timestamp: "11/06/2026 09:00",
        resolved: false,
      },
    ],
  },
  rt3: {
    taskId: "rt3",
    item: { title: "学习", lang: "zh", type: "word", contentStatus: "draft" },
    authorName: "Duy Phạm",
    assigneeName: "Minh Anh",
    priority: "high",
    status: "changes_requested",
    created: "09/06/2026 10:00",
    updated: "11/06/2026",
    changeCount: 7,
    diff: [
      { field: "zh_pinyin", before: "xuéxí", after: "xué xí" },
      { field: "vi_definition", before: "(trống)", after: "học tập, nghiên cứu" },
      { field: "example_zh", before: "(trống)", after: "他每天学习汉语。" },
    ],
    comments: [
      {
        id: "c1",
        author: "Duy Phạm",
        role: "author",
        text: "Đã thêm pinyin, định nghĩa tiếng Việt và ví dụ câu.",
        timestamp: "09/06/2026 10:00",
        resolved: false,
      },
      {
        id: "c2",
        author: "Minh Anh",
        role: "reviewer",
        text: "Pinyin cần có dấu thanh đầy đủ (xué xí). Ví dụ câu nên có bản dịch tiếng Việt.",
        timestamp: "10/06/2026 14:00",
        resolved: false,
        field: "Scripts",
        severity: "blocker",
      },
    ],
  },
};
