import type { AppNotification } from "./types";

const NOW = new Date("2026-06-23T08:00:00+07:00");
const h = (n: number) => new Date(NOW.getTime() - n * 3_600_000);
const d = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: "n1",
    type: "golden_time",
    title: "Golden Time sắp đến!",
    body: "Bộ nhớ của bạn đang ở đỉnh điểm. Ôn 12 từ ngay bây giờ để không bị mất tiến độ.",
    sentAt: h(0.5),
    openedAt: null,
    lang: "ja",
    action: "Bắt đầu Golden Time",
    dest: "/golden-time",
  },
  {
    id: "n2",
    type: "streak",
    title: "Chuỗi 7 ngày! Đừng để mất hôm nay",
    body: "Bạn đã học liên tục 7 ngày. Hoàn thành ít nhất 1 bài hôm nay để giữ chuỗi của mình.",
    sentAt: h(2),
    openedAt: null,
    lang: null,
    action: "Học ngay",
    dest: "/collections",
  },
  {
    id: "n3",
    type: "daily_goal",
    title: "Mục tiêu hôm nay đã hoàn thành!",
    body: "Bạn đã học 20 từ hôm nay — vượt mục tiêu hàng ngày. Thêm 10 từ nữa để tích thêm XP.",
    sentAt: h(5),
    openedAt: h(4),
    lang: null,
    action: "Xem thống kê",
    dest: "/stats",
  },
  {
    id: "n4",
    type: "golden_time",
    title: "5 từ cần ôn trong Golden Time",
    body: "Có 5 từ tiếng Anh đang chờ bạn ôn tập. Mỗi lần ôn đúng lúc giúp ghi nhớ lâu hơn gấp 4 lần.",
    sentAt: d(1),
    openedAt: null,
    lang: "en",
    action: "Ôn ngay",
    dest: "/golden-time",
  },
  {
    id: "n5",
    type: "payment",
    title: "Nâng cấp thành công lên Pro",
    body: "Tài khoản của bạn đã được nâng cấp lên LexiPath Pro. Tận hưởng toàn bộ bộ sưu tập và tính năng không giới hạn.",
    sentAt: d(1),
    openedAt: d(1),
    lang: null,
    action: "Xem tài khoản",
    dest: "/settings",
  },
  {
    id: "n6",
    type: "security",
    title: "Đăng nhập từ thiết bị mới",
    body: "Phát hiện đăng nhập từ thiết bị mới tại Hà Nội, Việt Nam. Nếu không phải bạn, hãy đổi mật khẩu ngay.",
    sentAt: d(2),
    openedAt: null,
    lang: null,
    action: "Kiểm tra bảo mật",
    dest: "/settings",
  },
  {
    id: "n7",
    type: "new_content",
    title: "Bộ sưu tập mới: JLPT N2 Kanji",
    body: "Bộ sưu tập JLPT N2 Kanji với 500 từ chính thức đã được thêm vào. Bắt đầu luyện tập ngay hôm nay.",
    sentAt: d(3),
    openedAt: d(3),
    lang: "ja",
    action: "Xem bộ sưu tập",
    dest: "/collections",
  },
  {
    id: "n8",
    type: "new_content",
    title: "Khóa học Business English đã cập nhật",
    body: "60 từ vựng mới về chủ đề thuyết trình và đàm phán đã được bổ sung vào khóa học Business English.",
    sentAt: d(5),
    openedAt: d(5),
    lang: "en",
    action: "Tiếp tục học",
    dest: "/collections",
  },
  {
    id: "n9",
    type: "exam",
    title: "Nhắc nhở: Kỳ thi JLPT N3 còn 30 ngày",
    body: "Bạn còn 30 ngày để kỳ thi JLPT N3. Theo lộ trình hiện tại, bạn cần ôn thêm 40 từ để đạt mục tiêu.",
    sentAt: d(6),
    openedAt: null,
    lang: "ja",
    action: "Xem lộ trình",
    dest: "/collections",
  },
];
