import type { GoldenTimeExercise, GoldenTimeSessionMeta } from "./golden-time-session.types";

const GOLDEN_TIME_EXERCISES: GoldenTimeExercise[] = [
  {
    id: "gt-1",
    type: "choice",
    reason: "overdue",
    skillKey: "meaning",
    dueLabel: "Quá hạn 2 ngày",
    word: "accomplish",
    ipa: "/əˈkʌm.plɪʃ/",
    meaning: "hoàn thành, đạt được",
    pos: "verb",
    lang: "en-US",
    prompt: "Chọn nghĩa đúng của từ:",
    choices: [
      "hoàn thành, đạt được",
      "từ chối, phủ nhận",
      "tranh luận, phản đối",
      "mô tả, giải thích",
    ],
    correctChoiceIndex: 0,
    explanation:
      "'Accomplish' có nghĩa là hoàn thành hoặc đạt được điều gì đó sau nhiều nỗ lực.",
    xpReward: 12,
  },
  {
    id: "gt-2",
    type: "audio",
    reason: "exam_miss",
    skillKey: "listening",
    word: "determine",
    ipa: "/dɪˈtɜː.mɪn/",
    meaning: "xác định, quyết tâm",
    pos: "verb",
    lang: "en-US",
    prompt: "Nghe và chọn từ bạn vừa nghe:",
    choices: ["determine", "terminate", "germinate", "denominate"],
    correctChoiceIndex: 0,
    explanation:
      "'Determine' có nghĩa là xác định hoặc quyết định điều gì đó một cách dứt khoát.",
    xpReward: 12,
  },
  {
    id: "gt-3",
    type: "fill_blank",
    reason: "weak",
    skillKey: "usage",
    word: "negotiate",
    ipa: "/nɪˈɡəʊ.ʃi.eɪt/",
    meaning: "đàm phán, thương lượng",
    pos: "verb",
    lang: "en-US",
    sentenceBefore: "The two sides agreed to",
    sentenceAfter: "a new trade deal.",
    correctAnswer: "negotiate",
    explanation:
      "'Negotiate' được dùng khi hai bên thảo luận để đạt được thỏa thuận.",
    xpReward: 15,
  },
  {
    id: "gt-4",
    type: "collocation",
    reason: "due",
    skillKey: "collocation",
    dueLabel: "Hôm nay",
    word: "revenue",
    ipa: "/ˈrev.ə.njuː/",
    meaning: "doanh thu, nguồn thu",
    pos: "noun",
    lang: "en-US",
    prompt: "Chọn cụm từ đúng đi với 'revenue':",
    baseWord: "revenue",
    collocationOptions: [
      "generate revenue",
      "make revenue",
      "do revenue",
      "create revenue",
    ],
    correctCollocationIndex: 0,
    explanation:
      "'Generate revenue' (tạo ra doanh thu) là cụm cố định đúng. 'Make/do/create revenue' không tự nhiên trong tiếng Anh kinh doanh.",
    xpReward: 15,
  },
  {
    id: "gt-5",
    type: "spelling",
    reason: "due",
    skillKey: "spelling",
    dueLabel: "Hôm nay",
    word: "persevere",
    ipa: "/ˌpɜː.sɪˈvɪər/",
    meaning: "kiên trì, bền bỉ",
    pos: "verb",
    lang: "en-US",
    prompt: "Nghe phát âm và gõ lại từ:",
    hint: "Gợi ý: p _ r s _ v _ r _",
    correctAnswer: "persevere",
    explanation:
      "'Persevere' có nghĩa là tiếp tục nỗ lực dù gặp khó khăn — chú ý cách viết: per-se-vere.",
    xpReward: 18,
  },
  {
    id: "gt-6",
    type: "choice",
    reason: "weak",
    skillKey: "meaning",
    word: "collaborate",
    ipa: "/kəˈlæb.ər.eɪt/",
    meaning: "cộng tác, hợp tác",
    pos: "verb",
    lang: "en-US",
    prompt: "Chọn nghĩa đúng của từ:",
    choices: [
      "cộng tác, hợp tác",
      "cạnh tranh, đối đầu",
      "phê bình, chỉ trích",
      "suy nghĩ, cân nhắc",
    ],
    correctChoiceIndex: 0,
    explanation:
      "'Collaborate' nghĩa là làm việc cùng nhau hướng đến một mục tiêu chung.",
    xpReward: 12,
  },
  {
    id: "gt-7",
    type: "fill_blank",
    reason: "overdue",
    skillKey: "usage",
    dueLabel: "Quá hạn 1 ngày",
    word: "initiative",
    ipa: "/ɪˈnɪʃ.ə.tɪv/",
    meaning: "sáng kiến, chủ động",
    pos: "noun",
    lang: "en-US",
    sentenceBefore: "She took the",
    sentenceAfter: "to launch the new campaign.",
    correctAnswer: "initiative",
    explanation:
      "'Take the initiative' (chủ động ra tay trước) là cụm cố định phổ biến trong tiếng Anh.",
    xpReward: 15,
  },
  {
    id: "gt-8",
    type: "audio",
    reason: "due",
    skillKey: "listening",
    dueLabel: "Hôm nay",
    word: "implement",
    ipa: "/ˈɪm.plɪ.ment/",
    meaning: "thực hiện, triển khai",
    pos: "verb",
    lang: "en-US",
    prompt: "Nghe và chọn từ bạn vừa nghe:",
    choices: ["implement", "compliment", "supplement", "replicate"],
    correctChoiceIndex: 0,
    explanation:
      "'Implement' có nghĩa là đưa vào thực tế, triển khai một kế hoạch hay quyết định.",
    xpReward: 12,
  },
];

export function getMockGoldenTimeSession(sessionId: string): {
  exercises: GoldenTimeExercise[];
  meta: GoldenTimeSessionMeta;
} {
  return {
    exercises: GOLDEN_TIME_EXERCISES,
    meta: {
      sessionId,
      lessonTitle: "Golden Time",
      queueCount: GOLDEN_TIME_EXERCISES.length,
      windowMessage: "Ôn đúng thời điểm — trước khi quên · ~7 phút",
      lang: "en-US",
      returnHref: "/golden-time",
    },
  };
}
