import type {
  AccountLockRecord,
  DeviceRecord,
  SecurityEventRecord,
  SessionRecord,
} from "./types";

export const MOCK_SESSIONS: SessionRecord[] = [
  {
    id: "ses_1",
    user: "Minh Anh",
    email: "minhanh@gmail.com",
    device: "MacBook Pro · Chrome",
    type: "desktop",
    ip: "113.161.44.2",
    location: "Hồ Chí Minh, VN",
    started: "Hôm nay 08:01",
    lastActive: "Đang hoạt động",
    current: true,
    risk: "low",
  },
  {
    id: "ses_2",
    user: "Minh Anh",
    email: "minhanh@gmail.com",
    device: "iPhone 15 · Safari",
    type: "mobile",
    ip: "113.161.44.9",
    location: "Hồ Chí Minh, VN",
    started: "Hôm nay 07:30",
    lastActive: "2 giờ trước",
    current: false,
    risk: "low",
  },
  {
    id: "ses_3",
    user: "Tuấn Võ",
    email: "tuanvo@gmail.com",
    device: "Windows PC · Edge",
    type: "desktop",
    ip: "45.119.82.140",
    location: "Singapore",
    started: "Hôm nay 09:08",
    lastActive: "5 phút trước",
    current: false,
    risk: "high",
  },
  {
    id: "ses_4",
    user: "Hoàng Lê",
    email: "hoangle@gmail.com",
    device: "Galaxy S24 · Chrome",
    type: "mobile",
    ip: "171.250.30.11",
    location: "Đà Nẵng, VN",
    started: "Hôm qua 21:40",
    lastActive: "3 giờ trước",
    current: false,
    risk: "medium",
  },
  {
    id: "ses_5",
    user: "Thảo Nguyễn",
    email: "thaonguyen@gmail.com",
    device: "iPad Air · Safari",
    type: "tablet",
    ip: "113.161.44.18",
    location: "Hồ Chí Minh, VN",
    started: "Hôm qua 18:25",
    lastActive: "1 ngày trước",
    current: false,
    risk: "low",
  },
];

export const MOCK_DEVICES: DeviceRecord[] = [
  {
    id: "dev_1",
    user: "Minh Anh",
    name: "MacBook Pro 16″",
    type: "desktop",
    os: "macOS 15.3",
    browser: "Chrome 128",
    firstSeen: "12/01/2026",
    lastSeen: "Hôm nay",
    trusted: true,
    sessions: 2,
  },
  {
    id: "dev_2",
    user: "Minh Anh",
    name: "iPhone 15",
    type: "mobile",
    os: "iOS 18.2",
    browser: "Safari",
    firstSeen: "12/01/2026",
    lastSeen: "2 giờ trước",
    trusted: true,
    sessions: 1,
  },
  {
    id: "dev_3",
    user: "Tuấn Võ",
    name: "Windows PC",
    type: "desktop",
    os: "Windows 11",
    browser: "Edge 128",
    firstSeen: "Hôm nay",
    lastSeen: "5 phút trước",
    trusted: false,
    sessions: 1,
  },
  {
    id: "dev_4",
    user: "Hoàng Lê",
    name: "Galaxy S24",
    type: "mobile",
    os: "Android 14",
    browser: "Chrome 128",
    firstSeen: "03/03/2026",
    lastSeen: "3 giờ trước",
    trusted: true,
    sessions: 1,
  },
  {
    id: "dev_5",
    user: "Thảo Nguyễn",
    name: "iPad Air",
    type: "tablet",
    os: "iPadOS 18",
    browser: "Safari",
    firstSeen: "21/02/2026",
    lastSeen: "1 ngày trước",
    trusted: true,
    sessions: 1,
  },
];

export const MOCK_SEC_EVENTS: SecurityEventRecord[] = [
  {
    id: "se_1",
    user: "Tuấn Võ",
    email: "tuanvo@gmail.com",
    event: "Đăng nhập thất bại 5 lần",
    type: "login_failed",
    description: "IP 45.119.82.140 (Singapore) — vượt ngưỡng cho phép.",
    timestamp: "Hôm nay 09:12",
    severity: "critical",
    risk: "high",
    ip: "45.119.82.140",
    location: "Singapore",
    device: "Windows PC · Edge",
  },
  {
    id: "se_2",
    user: "Tuấn Võ",
    email: "tuanvo@gmail.com",
    event: "Tài khoản bị khóa tạm thời",
    type: "account_locked",
    description: "Tự động khóa 30 phút sau nhiều lần đăng nhập sai.",
    timestamp: "Hôm nay 09:13",
    severity: "warning",
    risk: "high",
    ip: "45.119.82.140",
    location: "Singapore",
    device: "Windows PC · Edge",
  },
  {
    id: "se_3",
    user: "Hoàng Lê",
    email: "hoangle@gmail.com",
    event: "Đăng nhập từ vị trí mới",
    type: "new_location",
    description: "Đà Nẵng, VN — thiết bị đã từng dùng.",
    timestamp: "Hôm qua 21:40",
    severity: "warning",
    risk: "medium",
    ip: "171.250.30.11",
    location: "Đà Nẵng, VN",
    device: "Galaxy S24 · Chrome",
  },
  {
    id: "se_4",
    user: "Minh Anh",
    email: "minhanh@gmail.com",
    event: "Đổi mật khẩu thành công",
    type: "password_change",
    description: "Từ thiết bị đã xác thực (MacBook Pro).",
    timestamp: "Hôm nay 08:02",
    severity: "info",
    risk: "low",
    device: "MacBook Pro · Chrome",
    ip: "113.161.44.2",
    location: "Hồ Chí Minh, VN",
  },
  {
    id: "se_5",
    user: "Thảo Nguyễn",
    email: "thaonguyen@gmail.com",
    event: "Bật xác thực 2 lớp",
    type: "mfa_enabled",
    description: "Ứng dụng xác thực (TOTP) đã được kích hoạt.",
    timestamp: "Hôm qua 18:25",
    severity: "info",
    risk: "low",
    device: "iPad Air · Safari",
    ip: "113.161.44.18",
    location: "Hồ Chí Minh, VN",
  },
];

export const MOCK_ACCOUNT_LOCKS: AccountLockRecord[] = [
  {
    id: "lk_1",
    user: "Tuấn Võ",
    email: "tuanvo@gmail.com",
    reason: "Đăng nhập thất bại nhiều lần",
    type: "auto",
    status: "active",
    lockedAt: "Hôm nay 09:13",
    unlockAt: "Hôm nay 09:43",
    by: "Hệ thống",
  },
  {
    id: "lk_2",
    user: "Spam Bot",
    email: "bot9981@temp.io",
    reason: "Hoạt động đáng ngờ (bot)",
    type: "manual",
    status: "active",
    lockedAt: "Hôm qua 14:20",
    unlockAt: "—",
    by: "Tuấn Võ",
  },
  {
    id: "lk_3",
    user: "An Nguyễn",
    email: "an@gmail.com",
    reason: "Tranh chấp thanh toán",
    type: "manual",
    status: "released",
    lockedAt: "05/06/2026",
    unlockAt: "06/06/2026",
    by: "Duy Phạm",
  },
];
